module.exports = {
  populationSize: 20,
  maxGenerations: 200,
  targetFitness: 300,
  inputs: 9,
  outputs: 3,
  compatibilityThreshold: 3.0,
  c1: 1.0,
  c2: 1.0,
  c3: 0.4,
  weightMutateRate: 0.8,
  weightPerturbRate: 0.9,
  weightPerturbStrength: 0.3,
  addNodeRate: 0.03,
  addConnectionRate: 0.05,
  disableRate: 0.1,
  elitismCount: 2,
  survivalThreshold: 0.2,
  staleGenerationLimit: 15,
};
